//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkCarsharing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Reflection;

    public partial class CarsharingBDEntities : DbContext
    {
        private static CarsharingBDEntities _context;
        private static readonly object _lock = new object();

        public CarsharingBDEntities()
            : base("name=CarsharingBDEntities")
        {
        }

        public static CarsharingBDEntities GetContext()
        {
            lock (_lock)
            {
                if (_context == null || IsDisposed(_context))
                {
                    _context = new CarsharingBDEntities();
                }
                return _context;
            }
        }

        private static bool IsDisposed(DbContext context)
        {
            var disposedProperty = typeof(DbContext).GetProperty("Disposed",
                BindingFlags.NonPublic | BindingFlags.Instance);
            return (bool)disposedProperty.GetValue(context);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Auto> Autoes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Parking> Parkings { get; set; }
        public virtual DbSet<pricingPlan> pricingPlans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserData> UserDatas { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}