//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkCarsharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AutoID { get; set; }
        public Nullable<int> PricingPlanID { get; set; }
        public Nullable<int> ParkingID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Parking Parking { get; set; }
        public virtual pricingPlan pricingPlan { get; set; }
        public virtual User User { get; set; }
    }
}
