//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkCarsharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int UserDataID { get; set; }
        public int UserID { get; set; }
        public string PassportSerial { get; set; }
        public string PassportNumber { get; set; }
        public string PassportIssuedBy { get; set; }
        public Nullable<System.DateTime> PassportExpirationDate { get; set; }
        public string Pasport_Unit_code { get; set; }
        public string Drive_license_serial { get; set; }
        public string Drive_license_number { get; set; }
        public Nullable<System.DateTime> Drive_license_date { get; set; }
        public Nullable<System.DateTime> End_drive_license_date { get; set; }
        public string Drive_Unit_code { get; set; }
        public string Experience { get; set; }
        public string Drive_license_Category { get; set; }
    
        public virtual User User { get; set; }
    }
}
