//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkCarsharing
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string PassportNumber { get; set; }
        public string PassportIssuedBy { get; set; }
        public System.DateTime PassportIssueDate { get; set; }
        public Nullable<System.DateTime> PassportExpirationDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
